events { }
http {
    upstream quote_app {
        server quote-app-1:5000;
        server quote-app-2:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://quote_app;
            proxy_set_header Host $host;
        }
    }
}